### ISSUE TITLE
Cannot find name 'KnockoutObservable' when updating from v1.0.69

### ISSUE THREAD

**Issue by carstenbaumhoegger** [surveyjs/survey-creator#472]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

`node_modules/surveyjs-editor/surveyeditor.d.ts(1549,16): error TS2304: Cannot find name 'KnockoutObservableArray'..`

### What is the expected behavior?

Angular compiles as before

### How would you reproduce the current behavior (if this is a bug)?

I've update `surveyjs` from v1.0.69 to 1.0.72 and this error appears.
If I downgrade to v1.0.71 the error is still present.
If I downgrade to v1.0.69 again, everything works as expected.

### Specify your

* browser: Chrome
* editor version: 1.0.72

**Comment by tsv2013** [comment]
Can you try to remove the `node_modules` folder and reinstall packages via `npm i`?

**Comment by carstenbaumhoegger** [comment]
I did this a few times but this didn't solve the problem, error is still the same.

**Comment by tsv2013** [comment]
Could you you provide us with the steps to reproduce the issue on our side?

**Comment by tsv2013** [comment]
I've just cloned this repo (https://github.com/surveyjs/surveyjs_angular_cli) and run "npm i" and "ng serve" commands.

Everithing compiles and run ok for me.

**Comment by carstenbaumhoegger** [comment]
We were able to figure out, what is causing this issue.
When updating surveyjs, knockout get's updated to `3.5.0`, because surveyjs requires `"knockout": ^3.4.0`.
We are now pinning `knockout` to `3.4.2` and can update without any problems.

Should I report this problem to the knockout-team?

**Comment by tsv2013** [comment]
Sorry for the late response
No, IMO we need to upgrade dependencies

**Comment by andrewtelnov** [comment]
@carstenbaumhoegger We are using knockout v3.5 now.
