### ISSUE TITLE
ERROR Error - ASSERTION ERROR - Are we stuck in infinite loop

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#7293]
T25714 - SurveyJs Creator console error after migrating to v2.4.0
https://surveyjs.answerdesk.io/internal/ticket/details/T25714
```
installHook.js:1 ERROR Error: ASSERTION ERROR: Are we stuck in infinite loop? [Expected=> 999 < 1000 <=Actual]
    at throwError2 (root_effect_scheduler.mjs:351:11)
    at assertLessThan (root_effect_scheduler.mjs:322:9)
    at updateStylingMap (debug_node.mjs:26130:22)
    at checkStylingMap (debug_node.mjs:25728:13)
    at ɵɵstyleMap (debug_node.mjs:25605:5)
    at DesignerSurveyComponent_ng_template_0_Template (survey-creator-angular.js:508:8)
    at executeTemplate (debug_node.mjs:7929:9)
    at refreshView (debug_node.mjs:8959:13)
    at detectChangesInView (debug_node.mjs:9179:9)
    at detectChangesInViewIfAttached (debug_node.mjs:9139:5)
```
The issue is reproducible on any CodeSandbox Angular Demo, for instance: [NPS Survey Question](https://surveyjs.io/survey-creator/examples/free-nps-survey-template/angular).

[View CodeSandbox](https://codesandbox.io/p/sandbox/mpsnld?file=%2Fsrc%2Fapp%2Fcomponents%2Fcreator.component.ts)

<img width="2560" height="1239" alt="Image" src="https://github.com/user-attachments/assets/79647a8f-e147-4dc6-8115-d30e28614e6b" />
