### ISSUE TITLE
Creator for React - Property 'text' does not exist on type 'SurveyCreator' TypeScript Compile Error 

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3712]
The following exception is thrown on an attempt to run the `react-scripts build` command for a Survey Creator React app:
```
TS2339: Property 'text' does not exist on type 'SurveyCreator'.
    24 |
    25 |   const creator = new SurveyCreator();
  > 26 |   creator.text = JSON.stringify(survey);
       |           ^^^^
    27 |
    28 |   return (
    29 |       <div className="App">
```

Original issue: [T11442 - After upgrade to 1.9.61 typescript stop compiling](https://surveyjs.answerdesk.io/internal/ticket/details/T11442)
